# Generated by Django 5.1.3 on 2024-11-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
