# Generated by Django 5.1.3 on 2024-11-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_user_photo_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
