# Generated by Django 5.0.6 on 2024-12-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_remove_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question',
            new_name='question_id',
        ),
        migrations.AddField(
            model_name='response',
            name='original_answer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
