# Generated by Django 5.0.6 on 2024-12-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0007_rename_question_response_question_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='original_answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='score',
        ),
    ]
