# Generated by Django 5.0.6 on 2024-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0008_rename_question_id_response_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question',
            new_name='question_id',
        ),
        migrations.AddField(
            model_name='response',
            name='original_answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
