# Generated by Django 5.0.6 on 2024-12-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0009_rename_question_response_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='original_answer',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='response',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
