# Generated by Django 5.0.6 on 2024-12-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0010_alter_response_original_answer_alter_response_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UsersResponses',
        ),
    ]
