# Generated by Django 5.0.6 on 2024-12-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0011_rename_response_usersresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.JSONField(default=dict),
        ),
    ]
