# Generated by Django 5.0.6 on 2024-12-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0012_question_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
