# Generated by Django 5.0.6 on 2024-12-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0013_delete_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersresponses',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UsersResponses',
        ),
    ]
