# Generated by Django 5.0.6 on 2024-12-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('keywords', models.JSONField(default=dict)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admin_dashboard.jobpost')),
            ],
        ),
    ]
