# Generated by Django 5.0.6 on 2024-12-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='questions_csv',
            field=models.FileField(blank=True, null=True, upload_to='job_questions/'),
        ),
    ]
