# Generated by Django 5.0.6 on 2024-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_jobpost_questions_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='job_post',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
