# Generated by Django 5.0.6 on 2024-12-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_remove_question_job_post_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='command_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='command_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='job_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='admin_dashboard.jobpost'),
            preserve_default=False,
        ),
    ]
