# Generated by Django 5.0.6 on 2024-12-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_jobpost_command_id_question_command_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='command_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
