# Generated by Django 5.0.6 on 2024-12-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_question_command_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField()),
                ('user_answer', models.TextField()),
                ('original_answer', models.TextField(default='Not Provided')),
                ('score', models.IntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.question')),
            ],
        ),
    ]
